### ISSUE TITLE
Switch to `From` when converting enum -> value

### ISSUE THREAD

**Issue by nyurik** [matthewjberger/enum2repr#2]
Is there a reason why you have `impl TryFrom<enum_name> for <integer>` ?  What can fail?  If nothing can ever fail, I think a simpler `From` impl is much cleaner and more performant.

**Comment by matthewjberger** [comment]
Good point, I'll update this soon 🙏

**Comment by matthewjberger** [comment]
Fixed in [this commit](https://github.com/matthewjberger/enum2repr/commit/157db516048052fc321ccc00a088eaba0238ca6e) 🚀
